### ISSUE TITLE
openGL error for X forwarding mistral - mac

### ISSUE THREAD

**Issue by florianziemen** [psyplot/psyplot-gui#27]
When I start psyplot on mistral.dkrz.de from my laptop, I get these error messages.
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```

That can be fixed following 
https://unix.stackexchange.com/questions/429760/opengl-rendering-with-x11-forwarding
On the mac (command line)
```
quartz-wm --help
```
will yield something like `(default: org.xquartz.X11)` in its lowest line of output. Use that output in
```
defaults write org.xquartz.X11(or whatever you got) enable_iglx -bool true 3
```
restart Xquartz

**Comment by Chilipp** [comment]
thanks for documenting this issue @florianziemen! I suppose we can close it as you already found the solution? Or is there more to it?

**Comment by florianziemen** [comment]
Yes, I think you can close it. If you can catch the error, an error message with a hint for solving it would be good, but the problem is not in psyplot and we have a solution.

Thanks for the help in finding the issue! :)

And thanks for psyplot!

Cheers

Flo
