### ISSUE TITLE
Sphinx crashes when tempdir is on another drive on Windows

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psyplot-gui#6]
#### Problem description

When the build directory for the help is on another drive than the library, psyplot crashes

#### Expected Output
Very likely due to the same reason as in https://github.com/spyder-ide/spyder/issues/6549, sphinx cannot handle it when the temporary build directory is on another drive on Windows. This affects `sphinx=2.2.0`. It is fixed by downgrading to `sphinx=1.7.5`.

**Comment by dkl78167816** [comment]
I meet the same error  as yours

**Comment by Chilipp** [comment]
Thanks for the info @dkl78167816! I did not check again because I was very busy the last few weeks and personally I am not using Windows. But I can have a look into it, soon.

What version of Sphinx are you using? Does it help to downgrade to 1.7.5?

**Comment by Chilipp** [comment]
just tested this on windows and it seems to not be an issue anymore
